"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$username\
$git_branch\
$git_status\
$git_metrics\
$all\
$directory\
$fill\
$cmd_duration\
$time\
$line_break\
$character
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[os]
disabled = false
format = '\[[$symbol]($style)\]'

[os.symbols]
Ubuntu = ""
Windows = ""

[shell]
disabled = false
bash_indicator = 'bash'
pwsh_indicator = 'pwsh'
format = '\[[ $indicator]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[username]
show_always = true
disabled = false
format = '\[[ $user]($style)\]'

[directory]
truncation_length = 8
truncation_symbol = '…/'
format = ' [ $path]($style)[$read_only]($read_only_style) '

[direnv]
format = '\[[$symbol$loaded/$allowed]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\[[\($hash$tag\)]($style)\]'

[git_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '\[[$state ($progress_current/$progress_total)]($style)\]'

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\])'

[hostname]
ssh_symbol = '󰣀'
format = '\[[$ssh_symbol($hostname)]($style)\] '

[localip]
format = '\[[$localipv4]($style)\]'

[memory_usage]
symbol = ''
format = '\[$symbol[$ram( | $swap)]($style)\]'

[dotnet]
symbol = ''
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[java]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[nodejs]
symbol = '󰎙'
format = '\[󰎙 [$symbol($version)]($style)\]'

[python]
symbol = ''
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[docker_context]
symbol = ''
format = '\[[$symbol$context]($style)\]'

[kubernetes]
symbol = ''
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[container]
symbol = ''
format = '\[[$symbol \[$name\]]($style)\]'

[helm]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[azure]
symbol = ''
format = '\[[$symbol($subscription)]($style)\]'

[aws]
symbol = ''
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[gcloud]
symbol = '󱇶'
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[terraform]
symbol = ''
format = '\[[$symbol$workspace]($style)\]'

[status]
format = '\[[$symbol$status]($style)\]'

[cmd_duration]
format = '\[[󱎫 $duration]($style)\]'

[time]
disabled = false
format = '\[[󰥔 $time]($style)\]'

